# Generated by Django 5.2.6 on 2026-02-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0006_household_head_gender_and_more'),
        ('savings_groups', '0004_businesssavingsgroup_savings_frequency_savingsrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bsgmember',
            unique_together={('bsg', 'household')},
        ),
        migrations.AddIndex(
            model_name='bsgmember',
            index=models.Index(fields=['role'], name='upg_bsg_mem_role_81c8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='bsgmember',
            index=models.Index(fields=['is_active'], name='upg_bsg_mem_is_acti_57f7db_idx'),
        ),
    ]
