# Generated by Django 5.2.6 on 2026-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_groups', '0007_bsgloan_loanrepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsgloan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='bsgloan',
            name='approved_date',
        ),
        migrations.AlterField(
            model_name='bsgloan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('partially_repaid', 'Partially Repaid'), ('fully_repaid', 'Fully Repaid'), ('defaulted', 'Defaulted')], default='active', max_length=20),
        ),
    ]
