# Generated by Django 5.2.6 on 2026-02-05 20:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('upg_grants', '0006_householdgrantapplication_business_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the grant program', max_length=200)),
                ('description', models.TextField(help_text='Description and eligibility criteria')),
                ('grant_type', models.CharField(choices=[('seed_business', 'Seed Business Grant'), ('performance_recognition', 'Performance Recognition Grant'), ('livelihood', 'Livelihood Grant'), ('emergency', 'Emergency Grant'), ('education', 'Education Support Grant'), ('housing', 'Housing Improvement Grant'), ('other', 'Other')], max_length=30)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_amount_per_beneficiary', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=10)),
                ('min_amount_per_beneficiary', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grant_programs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_programs', to='programs.program')),
            ],
            options={
                'verbose_name': 'Grant Program',
                'verbose_name_plural': 'Grant Programs',
                'db_table': 'upg_grant_programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantFieldAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_fa_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('field_associate', models.ForeignKey(limit_choices_to={'role': 'field_associate'}, on_delete=django.db.models.deletion.CASCADE, related_name='grant_fa_assignments', to=settings.AUTH_USER_MODEL)),
                ('grant_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_assignments', to='upg_grants.grantprogram')),
            ],
            options={
                'verbose_name': 'Grant Field Associate Assignment',
                'verbose_name_plural': 'Grant Field Associate Assignments',
                'db_table': 'upg_grant_field_associates',
                'unique_together': {('grant_program', 'field_associate')},
            },
        ),
        migrations.CreateModel(
            name='GrantMentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_mentor_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('grant_fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='upg_grants.grantfieldassociate')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='grant_mentor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Mentor Assignment',
                'verbose_name_plural': 'Grant Mentor Assignments',
                'db_table': 'upg_grant_mentor_assignments',
                'unique_together': {('grant_fa', 'mentor')},
            },
        ),
    ]
