# Generated by Django 5.2.6 on 2026-02-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upg_grants', '0007_add_grant_assignment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdgrantapplication',
            name='grant_program',
            field=models.ForeignKey(blank=True, help_text='Grant program this application was submitted under', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='upg_grants.grantprogram'),
        ),
    ]
