# Generated by Django 5.2.6 on 2026-01-08 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_groups', '0001_initial'),
        ('forms', '0001_initial'),
        ('households', '0005_household_constituency_household_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('form_create', 'Form Create'), ('form_update', 'Form Update'), ('form_delete', 'Form Delete'), ('reference_data_push', 'Reference Data Push'), ('submission_receive', 'Submission Receive')], max_length=30)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('kobo_asset_uid', models.CharField(blank=True, max_length=100)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'upg_kobo_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KoboWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_asset_uid', models.CharField(max_length=100)),
                ('submission_uuid', models.CharField(max_length=100, unique=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('processed_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'upg_kobo_webhook_logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='data_source',
            field=models.CharField(choices=[('web_form', 'Web Form'), ('kobo_sync', 'KoboToolbox Sync'), ('mobile_app', 'Mobile App'), ('api', 'API')], default='web_form', help_text='Source of this submission', max_length=20),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='kobo_submission_time',
            field=models.DateTimeField(blank=True, help_text='Original submission timestamp from Kobo', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='kobo_submission_uuid',
            field=models.CharField(blank=True, help_text='UUID from KoboToolbox submission', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='kobo_asset_uid',
            field=models.CharField(blank=True, help_text='KoboToolbox Asset UID (auto-generated on sync)', max_length=100),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='kobo_form_url',
            field=models.URLField(blank=True, help_text='Direct link to form in KoboToolbox'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='kobo_sync_status',
            field=models.CharField(choices=[('never_synced', 'Never Synced'), ('synced', 'Synced'), ('sync_pending', 'Sync Pending'), ('sync_failed', 'Sync Failed'), ('sync_outdated', 'Sync Outdated')], default='never_synced', help_text='Current sync status with KoboToolbox', max_length=20),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='kobo_version',
            field=models.IntegerField(default=1, help_text='Version counter for tracking form updates'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if failed'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful sync to Kobo', null=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='sync_to_kobo',
            field=models.BooleanField(default=False, help_text='Enable sync with KoboToolbox for offline data collection'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['kobo_submission_uuid'], name='upg_form_su_kobo_su_35efa7_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['data_source'], name='upg_form_su_data_so_38bbde_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['sync_to_kobo', 'kobo_sync_status'], name='upg_form_te_sync_to_0f1593_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['kobo_asset_uid'], name='upg_form_te_kobo_as_618528_idx'),
        ),
        migrations.AddField(
            model_name='kobosynclog',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='forms.formtemplate'),
        ),
        migrations.AddField(
            model_name='kobosynclog',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kobowebhooklog',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.formsubmission'),
        ),
        migrations.AddField(
            model_name='kobowebhooklog',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.formtemplate'),
        ),
        migrations.AddIndex(
            model_name='kobosynclog',
            index=models.Index(fields=['sync_type', 'status'], name='upg_kobo_sy_sync_ty_76fd36_idx'),
        ),
        migrations.AddIndex(
            model_name='kobosynclog',
            index=models.Index(fields=['started_at'], name='upg_kobo_sy_started_5e6572_idx'),
        ),
        migrations.AddIndex(
            model_name='kobowebhooklog',
            index=models.Index(fields=['kobo_asset_uid'], name='upg_kobo_we_kobo_as_309037_idx'),
        ),
        migrations.AddIndex(
            model_name='kobowebhooklog',
            index=models.Index(fields=['submission_uuid'], name='upg_kobo_we_submiss_10759a_idx'),
        ),
        migrations.AddIndex(
            model_name='kobowebhooklog',
            index=models.Index(fields=['status'], name='upg_kobo_we_status_337a8f_idx'),
        ),
    ]
