# Generated by Django 5.2.6 on 2026-01-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_kobosynclog_kobowebhooklog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input (Short)'), ('textarea', 'Text Area (Long)'), ('note', 'Note/Display Text'), ('number', 'Number Input'), ('decimal', 'Decimal Number'), ('calculate', 'Calculated Field'), ('email', 'Email Input'), ('phone', 'Phone Number'), ('date', 'Date Picker'), ('time', 'Time Picker'), ('datetime', 'Date & Time'), ('select', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes (Multiple)'), ('boolean', 'Yes/No'), ('file', 'File Upload'), ('image', 'Image/Photo Upload'), ('audio', 'Audio Recording'), ('video', 'Video Recording'), ('rating', 'Rating Scale (1-5)'), ('location', 'GPS Location (Lat/Long)'), ('signature', 'Digital Signature'), ('barcode', 'Barcode/QR Scanner'), ('range', 'Range Slider'), ('section', 'Section Header'), ('group', 'Field Group')], max_length=20),
        ),
    ]
