# Generated by Django 5.2.6 on 2026-01-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formassignment'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formtemplate'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='kobo_submission_uuid',
            field=models.CharField(blank=True, help_text='UUID from KoboToolbox submission', max_length=100, null=True, unique=True),
        ),
    ]
