# Generated by Django 5.2.6 on 2026-01-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_allow_null_assignment_and_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_label',
            field=models.CharField(max_length=500),
        ),
    ]
