# Generated by Django 5.2.6 on 2026-01-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_increase_field_label_length'),
        ('households', '0005_household_constituency_household_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='matched_household',
            field=models.ForeignKey(blank=True, help_text='Household matched during validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_matches', to='households.household'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='validation_message',
            field=models.TextField(blank=True, help_text='Details about the validation result'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='validation_status',
            field=models.CharField(choices=[('not_validated', 'Not Validated'), ('beneficiary_found', 'Beneficiary Found'), ('beneficiary_not_found', 'Beneficiary Not Found'), ('duplicate_detected', 'Duplicate Detected'), ('data_updated', 'Data Updated')], default='not_validated', help_text='Result of MIS validation check', max_length=30),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='field_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Maps form field names to MIS fields for validation. Example: {'id_number': 'head_id_number', 'phone': 'head_phone_number', 'village': 'village'}"),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='form_purpose',
            field=models.CharField(choices=[('general', 'General Form (No Validation)'), ('new_registration', 'New Beneficiary Registration'), ('program_enrollment', 'Program Enrollment'), ('survey', 'Survey/Assessment'), ('update_details', 'Update Beneficiary Details')], default='general', help_text='Determines how submissions are validated against MIS data', max_length=30),
        ),
    ]
