# Generated by Django 5.2.6 on 2026-02-18 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_systemsettings'),
        ('households', '0006_household_head_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('cycle_number', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'esr_bm_cycles',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esr_constituencies', to='core.county')),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'db_table': 'esr_constituencies',
                'unique_together': {('name', 'county')},
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='esr_import.constituency')),
            ],
            options={
                'db_table': 'esr_districts',
                'unique_together': {('name', 'constituency')},
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='esr_import.district')),
            ],
            options={
                'db_table': 'esr_divisions',
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.CreateModel(
            name='ESRHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('id_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('landmark', models.TextField(blank=True)),
                ('main_caregiver', models.CharField(blank=True, max_length=200)),
                ('number_of_members', models.IntegerField(default=1)),
                ('no_of_habitable_rooms', models.IntegerField(blank=True, null=True)),
                ('dwelling_tenure', models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('family', 'Family'), ('squatter', 'Squatter'), ('other', 'Other')], max_length=20)),
                ('roof_type', models.CharField(blank=True, choices=[('iron_sheets', 'Iron Sheets'), ('tiles', 'Tiles'), ('concrete', 'Concrete'), ('thatch', 'Thatch'), ('mud', 'Mud'), ('other', 'Other')], max_length=20)),
                ('wall_type', models.CharField(blank=True, choices=[('brick', 'Brick'), ('stone', 'Stone'), ('mud', 'Mud'), ('wood', 'Wood'), ('iron_sheets', 'Iron Sheets'), ('other', 'Other')], max_length=20)),
                ('floor_type', models.CharField(blank=True, choices=[('cement', 'Cement'), ('tiles', 'Tiles'), ('mud', 'Mud'), ('wood', 'Wood'), ('other', 'Other')], max_length=20)),
                ('dwelling_risk', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('lighting_fuel', models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('solar', 'Solar'), ('kerosene', 'Kerosene'), ('candle', 'Candle'), ('firewood', 'Firewood'), ('none', 'None'), ('other', 'Other')], max_length=20)),
                ('water_source', models.CharField(blank=True, choices=[('piped', 'Piped'), ('borehole', 'Borehole'), ('well', 'Well'), ('spring', 'Spring'), ('river', 'River'), ('rain', 'Rain'), ('vendor', 'Vendor'), ('other', 'Other')], max_length=20)),
                ('waste_disposal', models.CharField(blank=True, choices=[('flush_toilet', 'Flush Toilet'), ('pit_latrine', 'Pit Latrine'), ('vip_latrine', 'VIP Latrine'), ('bush', 'Bush'), ('shared', 'Shared'), ('none', 'None'), ('other', 'Other')], max_length=20)),
                ('cooking_fuel', models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('kerosene', 'Kerosene'), ('charcoal', 'Charcoal'), ('firewood', 'Firewood'), ('other', 'Other')], max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('import_batch_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bm_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='esr_import.bmcycle')),
                ('core_household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esr_households', to='households.household')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esr_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'esr_households',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ESRHouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship_to_head', models.CharField(blank=True, choices=[('head', 'Head'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('relative', 'Relative'), ('other', 'Other')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('is_head', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='esr_import.esrhousehold')),
            ],
            options={
                'db_table': 'esr_household_members',
            },
        ),
        migrations.CreateModel(
            name='ESRImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('duplicates', models.IntegerField(default=0)),
                ('villages_created', models.IntegerField(default=0)),
                ('mentors_created', models.IntegerField(default=0)),
                ('supervisors_created', models.IntegerField(default=0)),
                ('households_created', models.IntegerField(default=0)),
                ('bm_cycles_created', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='processing', max_length=30)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('mentor_credentials', models.JSONField(blank=True, default=list)),
                ('supervisor_credentials', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esr_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'esr_import_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ESRVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('landmark', models.TextField(blank=True)),
                ('community_leader_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('core_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esr_villages', to='core.village')),
            ],
            options={
                'db_table': 'esr_villages',
            },
        ),
        migrations.AddField(
            model_name='esrhousehold',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='esr_import.esrvillage'),
        ),
        migrations.CreateModel(
            name='ESRWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='esr_import.division')),
            ],
            options={
                'db_table': 'esr_wards',
                'unique_together': {('name', 'division')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='esr_import.esrward')),
            ],
            options={
                'db_table': 'esr_locations',
                'unique_together': {('name', 'ward')},
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('profile_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esr_mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'esr_mentor_profiles',
            },
        ),
        migrations.AddField(
            model_name='esrhousehold',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='esr_import.mentorprofile'),
        ),
        migrations.CreateModel(
            name='MentorSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'esr_mentor_supervisors',
            },
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='esr_import.mentorsupervisor'),
        ),
        migrations.AddField(
            model_name='esrhousehold',
            name='mentor_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='esr_import.mentorsupervisor'),
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_locations', to='esr_import.location')),
            ],
            options={
                'db_table': 'esr_sub_locations',
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.AddField(
            model_name='esrvillage',
            name='sub_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='esr_import.sublocation'),
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bm_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='esr_import.bmcycle')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='esr_import.esrvillage')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_assignments', to='esr_import.mentorprofile')),
            ],
            options={
                'db_table': 'esr_mentor_assignments',
                'unique_together': {('mentor', 'village', 'bm_cycle')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='esrvillage',
            unique_together={('name', 'sub_location')},
        ),
    ]
