# Generated by Django 5.2.6 on 2026-01-15 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_village_subcounty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_api_url', models.URLField(default='https://kf.kobotoolbox.org/api/v2', help_text='KoboToolbox API URL')),
                ('kobo_api_token', models.CharField(blank=True, help_text='KoboToolbox API Token (from Account Settings > Security)', max_length=255)),
                ('kobo_base_url', models.URLField(default='https://kf.kobotoolbox.org', help_text='KoboToolbox Base URL')),
                ('kobo_webhook_secret', models.CharField(blank=True, help_text='Optional webhook secret for signature validation', max_length=255)),
                ('kobo_enabled', models.BooleanField(default=True, help_text='Enable/disable KoboToolbox integration')),
                ('sms_provider', models.CharField(blank=True, help_text='SMS provider name', max_length=50)),
                ('sms_api_key', models.CharField(blank=True, help_text='SMS provider API key', max_length=255)),
                ('sms_sender_id', models.CharField(blank=True, help_text='SMS sender ID', max_length=20)),
                ('organization_name', models.CharField(default='Village Enterprise', help_text='Organization name for reports', max_length=200)),
                ('timezone', models.CharField(default='Africa/Nairobi', help_text='System timezone', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'upg_system_settings',
            },
        ),
    ]
