# Generated by Django 5.2.6 on 2026-02-06 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings'),
        ('settings_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=dict, help_text='Module permissions configuration')),
                ('dashboard_type', models.CharField(choices=[('admin', 'Admin Dashboard'), ('executive', 'Executive Dashboard'), ('mentor', 'Mentor Dashboard'), ('me', 'M&E Dashboard'), ('field_associate', 'Field Associate Dashboard'), ('general', 'General Dashboard')], default='general', max_length=20)),
                ('geographic_scope', models.CharField(choices=[('all', 'All Villages (No Restriction)'), ('county', 'Specific County'), ('subcounty', 'Specific Sub-County'), ('villages', 'Specific Villages')], default='all', help_text='Define geographical access scope for this role', max_length=20)),
                ('allowed_subcounties', models.JSONField(blank=True, default=list, help_text='List of subcounty names this role can access')),
                ('allowed_county', models.CharField(blank=True, help_text='County this role can access', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_villages', models.ManyToManyField(blank=True, help_text="Villages this role can access (when scope is 'villages')", related_name='custom_roles', to='core.village')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_roles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_custom_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Role',
                'verbose_name_plural': 'Custom Roles',
                'db_table': 'upg_custom_roles',
                'ordering': ['name'],
            },
        ),
    ]
