# Generated by Django 5.2.6 on 2026-02-05 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this business group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
