# Generated by Django 5.2.6 on 2026-02-04 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Field Associate who supervises this user (for mentors)', limit_choices_to={'role': 'field_associate'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('county_executive', 'County Executive (CECM & Governor)'), ('county_assembly', 'County Assembly Member'), ('ict_admin', 'ICT Administrator'), ('program_manager', 'Program Manager'), ('me_staff', 'M&E Staff'), ('field_associate', 'Field Associate/Mentor Supervisor'), ('mentor', 'Mentor'), ('beneficiary', 'Beneficiary')], default='mentor', max_length=20),
        ),
    ]
