# Generated by Django 5.2.6 on 2026-02-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_supervisor_to_profile'),
        ('settings_module', '0002_add_custom_role_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='Custom role with specific permissions (used when role is set to "custom")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='settings_module.customrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('county_executive', 'County Executive (CECM & Governor)'), ('county_assembly', 'County Assembly Member'), ('ict_admin', 'ICT Administrator'), ('program_manager', 'Program Manager'), ('me_staff', 'M&E Staff'), ('field_associate', 'Field Associate/Mentor Supervisor'), ('mentor', 'Mentor'), ('beneficiary', 'Beneficiary'), ('custom', 'Custom Role')], default='mentor', max_length=20),
        ),
    ]
