# Generated by Django 5.2.6 on 2026-02-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings'),
        ('households', '0005_household_constituency_household_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='head_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['village'], name='upg_househo_village_eb3cac_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['head_id_number'], name='upg_househo_head_id_35d582_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['head_phone_number'], name='upg_househo_head_ph_75e6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['created_at'], name='upg_househo_created_d57312_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['relationship_to_head'], name='upg_househo_relatio_fd343b_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['gender'], name='upg_househo_gender_d759fe_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['is_program_participant'], name='upg_househo_is_prog_7bbe27_idx'),
        ),
    ]
