# Generated by Django 5.2.6 on 2026-02-18 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings'),
        ('households', '0006_household_head_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_households', to='core.mentor'),
        ),
        migrations.AddField(
            model_name='household',
            name='bm_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='core.businessmentorcycle'),
        ),
        migrations.AddField(
            model_name='household',
            name='cooking_fuel',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('kerosene', 'Kerosene'), ('charcoal', 'Charcoal'), ('firewood', 'Firewood'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='dwelling_risk',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='dwelling_tenure',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('family', 'Family'), ('squatter', 'Squatter'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='floor_type',
            field=models.CharField(blank=True, choices=[('cement', 'Cement'), ('tiles', 'Tiles'), ('mud', 'Mud'), ('wood', 'Wood'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='import_batch_id',
            field=models.CharField(blank=True, help_text='Import batch identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='landmark',
            field=models.CharField(blank=True, help_text='Landmark near the household', max_length=200),
        ),
        migrations.AddField(
            model_name='household',
            name='lighting_fuel',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('solar', 'Solar'), ('kerosene', 'Kerosene'), ('candle', 'Candle'), ('firewood', 'Firewood'), ('none', 'None'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='main_caregiver',
            field=models.CharField(blank=True, help_text='Main caregiver name', max_length=200),
        ),
        migrations.AddField(
            model_name='household',
            name='mentor_supervisor',
            field=models.ForeignKey(blank=True, help_text="Mentor's supervisor", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='no_of_habitable_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Number of habitable rooms', null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AddField(
            model_name='household',
            name='roof_type',
            field=models.CharField(blank=True, choices=[('iron_sheets', 'Iron Sheets'), ('tiles', 'Tiles'), ('concrete', 'Concrete'), ('thatch', 'Thatch'), ('mud', 'Mud'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='wall_type',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('stone', 'Stone'), ('mud', 'Mud'), ('wood', 'Wood'), ('iron_sheets', 'Iron Sheets'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='waste_disposal',
            field=models.CharField(blank=True, choices=[('flush_toilet', 'Flush Toilet'), ('pit_latrine', 'Pit Latrine'), ('vip_latrine', 'VIP Latrine'), ('bush', 'Bush'), ('shared', 'Shared'), ('none', 'None'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='water_source',
            field=models.CharField(blank=True, choices=[('piped', 'Piped'), ('borehole', 'Borehole'), ('well', 'Well'), ('spring', 'Spring'), ('river', 'River'), ('rain', 'Rain'), ('vendor', 'Vendor'), ('other', 'Other')], max_length=20),
        ),
    ]
