# Generated by Django 5.2.6 on 2026-01-08 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_village_subcounty'),
        ('households', '0005_household_constituency_household_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(db_index=True, help_text='National ID or Birth Certificate Number', max_length=20)),
                ('phone_number', models.CharField(help_text='Phone number for validation', max_length=20)),
                ('application_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('id_validation', 'ID Validation'), ('verification', 'Field Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=50, null=True)),
                ('screening_score', models.FloatField(blank=True, null=True)),
                ('screening_passed', models.BooleanField(blank=True, null=True)),
                ('screening_date', models.DateTimeField(blank=True, null=True)),
                ('screening_notes', models.TextField(blank=True, null=True)),
                ('id_validated', models.BooleanField(blank=True, null=True)),
                ('id_validation_date', models.DateTimeField(blank=True, null=True)),
                ('id_validation_response', models.JSONField(blank=True, null=True)),
                ('phone_validated', models.BooleanField(blank=True, null=True)),
                ('phone_validation_date', models.DateTimeField(blank=True, null=True)),
                ('poverty_score', models.FloatField(blank=True, null=True)),
                ('poverty_score_fetched_date', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_approved_applications', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_applications', to='households.household')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.program')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_submitted_applications', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_applications', to='core.village')),
            ],
            options={
                'db_table': 'upg_enrollment_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetingRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('logic_operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=10)),
                ('priority', models.IntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('group_weight', models.FloatField(default=1.0)),
                ('min_rules_to_pass', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='core.program')),
            ],
            options={
                'db_table': 'upg_targeting_rule_groups',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TargetingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('demographic', 'Demographic'), ('economic', 'Economic'), ('geographic', 'Geographic'), ('vulnerability', 'Vulnerability'), ('program', 'Program'), ('household', 'Household'), ('exclusion', 'Exclusion')], default='demographic', max_length=20)),
                ('rule_type', models.CharField(max_length=50)),
                ('field_path', models.CharField(blank=True, max_length=200, null=True)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('greater_than', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('lte', 'Less Than or Equal'), ('in', 'In'), ('not_in', 'Not In'), ('between', 'Between'), ('contains', 'Contains'), ('is_null', 'Is Null'), ('is_not_null', 'Is Not Null')], default='equals', max_length=20)),
                ('value', models.JSONField()),
                ('value_type', models.CharField(default='string', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
                ('score_on_pass', models.FloatField(default=10.0)),
                ('score_on_fail', models.FloatField(default=0.0)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('allow_override', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeting_rules', to='core.program')),
                ('rule_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='enrollment.targetingrulegroup')),
            ],
            options={
                'db_table': 'upg_targeting_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('verification_type', models.CharField(max_length=50)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_urls', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='enrollment.enrollmentapplication')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
