# Generated by Django 5.2.6 on 2026-01-08 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_village_subcounty'),
        ('households', '0005_household_constituency_household_district_and_more'),
        ('training', '0005_trainingattendance_attendance_marked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentoringvisit',
            options={'ordering': ['-visit_date']},
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='business_status',
            field=models.CharField(blank=True, choices=[('thriving', 'Thriving'), ('stable', 'Stable'), ('struggling', 'Struggling'), ('closed', 'Closed'), ('not_started', 'Not Started')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='challenges_faced',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='income_estimate',
            field=models.FloatField(blank=True, help_text='Estimated monthly income', null=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='location_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentoring_visits', to='core.program'),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='support_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='topics_discussed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mentoringvisit',
            name='visit_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentoringvisit',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentoringvisit',
            name='visit_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled Visit'), ('follow_up', 'Follow-up Visit'), ('emergency', 'Emergency Visit'), ('on_site', 'On-site'), ('phone', 'Phone Check'), ('virtual', 'Virtual')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('module_number', models.IntegerField(help_text='Order in sequence')),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topics covered')),
                ('materials_url', models.CharField(blank=True, max_length=500, null=True)),
                ('assessment_required', models.BooleanField(default=False)),
                ('is_sequential', models.BooleanField(default=True, help_text='Must complete previous module before this')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_modules', to='training.trainingmodule')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='core.program')),
            ],
            options={
                'db_table': 'upg_training_modules',
                'ordering': ['module_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.CharField(blank=True, max_length=500, null=True)),
                ('expected_participants', models.IntegerField(default=0)),
                ('actual_participants', models.IntegerField(default=0)),
                ('facilitator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], db_index=True, default='scheduled', max_length=20)),
                ('session_notes', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_sessions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.trainingmodule')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='core.program')),
            ],
            options={
                'db_table': 'upg_training_sessions',
                'ordering': ['-session_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(blank=True, default='full', max_length=50, null=True)),
                ('assessment_score', models.FloatField(blank=True, null=True)),
                ('assessment_passed', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_session_attendance', to='households.household')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_session_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to='training.trainingsession')),
            ],
            options={
                'db_table': 'upg_session_attendance',
                'ordering': ['-session__session_date'],
                'unique_together': {('session', 'household')},
            },
        ),
    ]
