# Generated by Django 5.2.6 on 2026-02-03 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings'),
        ('households', '0006_household_head_gender_and_more'),
        ('training', '0006_alter_mentoringvisit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingattendance',
            unique_together={('training', 'household', 'training_date')},
        ),
        migrations.AddIndex(
            model_name='mentoringvisit',
            index=models.Index(fields=['visit_date'], name='upg_mentori_visit_d_0fc713_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoringvisit',
            index=models.Index(fields=['household'], name='upg_mentori_househo_c8e58e_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoringvisit',
            index=models.Index(fields=['mentor'], name='upg_mentori_mentor__be278f_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoringvisit',
            index=models.Index(fields=['completed'], name='upg_mentori_complet_3b24f3_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['bm_cycle'], name='upg_trainin_bm_cycl_9dfb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['assigned_mentor'], name='upg_trainin_assigne_a6b72e_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['status'], name='upg_trainin_status_3833ba_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['start_date'], name='upg_trainin_start_d_a0e09b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['training_date'], name='upg_trainin_trainin_2d1250_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['attendance'], name='upg_trainin_attenda_9f8a8a_idx'),
        ),
    ]
